version: 2
jobs:
    build:
        working_directory: ~/vue-youtube-search
        docker:
            - image: circleci/node:8.15.0
        steps:
            - checkout
            - run:
                name: update-yarn
                command: yarn global add yarn@latest
            - restore_cache:
                name: Restore Yarn Package Cache
                keys:
                    - yarn-packages-{{ checksum "yarn.lock" }}
            - run:
                name: Install Dependencies
                command: yarn install --frozen-lockfile
            - save_cache:
                name: Save Yarn Package Cache
                key: yarn-packages-{{ checksum "yarn.lock" }}
                paths:
                    - ~/.cache/yarn
    test:
        working_directory: ~/vue-youtube-search
        docker:
            - image: circleci/node:8.15.0
        steps:
            - checkout
            - restore_cache:
                name: Restore Yarn Package Cache
                keys:
                    - yarn-packages-{{ checksum "yarn.lock" }}
            - run:
                name: Install Dependencies
                command: yarn install --frozen-lockfile
            - run:
                name: unit test
                command: yarn run test:unit
    deploy:
        working_directory: ~/vue-youtube-search
        docker:
            - image: circleci/node:8.15.0
        steps:
            - checkout
            - restore_cache:
                name: Restore Yarn Package Cache
                keys:
                    - yarn-packages-{{ checksum "yarn.lock" }}
            - run:
                name: Install Dependencies
                command: yarn install --frozen-lockfile
            - run:
                name: Setup Environment Variables
                command: |
                    echo ${VUE_APP_API_YOUTUBE_KEY} > ~/.env
                    echo ${VUE_APP_API_YOUTUBE_URL} > ~/.env
            - run:
                name: Deploy development branch to master
                command: |
                    chmod +x deploy.sh
                    ./deploy.sh
workflows:
    version: 2
    build_and_test_and_deploy:
        jobs:
            - build
            - test: 
                requires:
                    - build
            - deploy:
                requires:
                    - build
                    - test